modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cienticraft"
version="1.0.0"
displayName="cienticraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ADMIN, MCreator"

[[dependencies.cienticraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




